name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           docker pull madnight/docker-alpine-wkhtmltopdf || true
           docker build \
           --cache-from madnight/docker-alpine-wkhtmltopdf \
           -t qingpai/mutool:1.0.1-alpine .
           docker push qingpai/mutool:1.0.1-alpine
